spring:
  application:
    name: chaos-back

  datasource:
    url: jdbc:postgresql://localhost:5432/chaos_db
    username: postgres
    password: fabrica2024*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    servlet:
      mapping: /graphql
      enabled: true
    graphiql:
      enabled: true
      endpoint: /graphql
      path: /graphiql

  jwt:
    secret: 22341327198458621538721376214215432164821

server:
  port: 8081
